# Generated by Django 5.0.1 on 2024-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_tag_blog_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default_profile.jpeg', null=True, upload_to='profile_pics/')),
            ],
        ),
    ]
