# Generated by Django 5.0.1 on 2024-02-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
